server:
  port: 9090

#Datasource config
spring:
  datasource:
    url: jdbc:mysql://192.168.131.132:3306/flavor
    username: flavor
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# automatically execute script
  sql:
    init:
      mode: always
      continue-on-error: true
      username: flavor
      password: 123456
      encoding: utf-8
      schema-locations: classpath:initialize.sql
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd hh:mm:ss

#Mybatis-plus config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl